version: '3'

services:
  strapi:
    build: .
    container_name: portfolio_api
    restart: unless-stopped
    ports:
      - 1337:1337
    depends_on: 
      - postgres

  postgres:
    build: ./postgres
    container_name: portfolio_db
    restart: unless-stopped
    expose:
      - "5432"
    environment: 
      LC_ALL: ${LC_ALL}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - pgdata:/var/lib/postgresql/data/ 
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pg_admin
    depends_on:
      - postgres
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
volumes: 
  pgdata: